define([], function() {
  return {
    "PropertyPaneDescription": "Customize your web part",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "DateFieldLabel": "Date Field",
    "DateTimeFieldLabel": "Date Time Field",
    "PeopleFieldLabel": "People Picker Field",
    "GroupFieldLabel": "Group Picker Field",
    "SPListFieldLabel": "SharePoint List Field",
    "ColorFieldLabel": "Color Field",
    "ColorMiniFieldLabel": "Mini Color Field",
    "SPFolderFieldLabel": "SharePoint Folder Field",
    "PasswordFieldLabel": "Password Field",
    "FontFieldLabel": "Font Field",
    "FontSizeFieldLabel": "Font Size Field",
    "PhoneNumberFieldLabel": "Phone Number Field",
    "MaskedInputFieldLabel": "Masked Input Field",
    "GeoLocationFieldLabel": "Geolocation Field",
    "PictureFieldLabel": "Picture Field",
    "IconFieldLabel": "Icon Field",
    "DocumentFieldLabel": "Document Field",
    "DisplayModeFieldLabel": "Display Mode Field",
    "CustomListFieldLabel": "Custom List Field",
    "QueryFieldLabel": "List Query Field",
    "AlignFieldLabel": "Align Field",
    "DropDownSelectFieldLabel": "Drop down with select Field",
    "RichTextBoxFieldLabel": "Rich Text Box Field",
    "SliderRangeFieldLabel": "Slider Range Field",
    "DimensionFieldLabel": "Dimension Field",
    "SortableListFieldLabel": "Sortable List Field",
    "TreeViewFieldLabel": "TreeView Field",
    "DropDownTreeViewFieldLabel": "DropDown TreeView Field",
    "TagPickerFieldLabel": "Tag Picker Field",
    "StarRatingFieldLabel": "Star Rating Field",
    "NumericInputFieldLabel": "Numeric Input Field",
    "AutoSuggestFieldLabel": "Auto Complete Input Field",
    "SearchPropertiesFieldLabel": "Search Properties Picker",
    "OfficeVideoFieldLabel": "Office Video Field",
    "TermSetsFieldLabel": "Term Sets Field"
  }
});